### ISSUE TITLE
OCBuilder not up to date - current Version is 7.6.0

### ISSUE THREAD

**Issue by andistern** [yurikoles/homebrew-yurikoles#13]
see subject - details:
```
brew info ocbuilder
ocbuilder: 7.5.6 (auto_updates)
https://github.com/Pavo-IM/ocbuilder
Not installed
From: https://github.com/yurikoles/homebrew-yurikoles/blob/HEAD/Casks/ocbuilder.rb
==> Name
OCBuilder
==> Description
Compile OpenCore, common drivers and kexts
==> Artifacts
OCBuilder.app (App)

```

**Comment by andistern** [comment]
... also 7.5.6 fails compiling current version of OpenCore ...

**Comment by yurikoles** [comment]
OCBuilder has built-in update mechanism, which should pop up, so cask has `auto_updates true`, such casks are skipped during `brew upgrade`.

**Comment by yurikoles** [comment]
Closed via fba1495220288501c4c068f6c72f48ce3a6f2e66

**Comment by yurikoles** [comment]
> see subject - details:

You forgot to mention cask name in subject. This repo has few other casks and formulas.

**Comment by andistern** [comment]
sorry - just oriented my subject according to issue #5 - perhaps close that also ;-))
