### ISSUE TITLE
Keybard on konsole

### ISSUE THREAD

**Issue by marcovc** [yurikoles/homebrew-yurikoles#17]
Hi,

Not sure if this is the right place to ask. I've installed kde/konsole on my mac, but the ctrl key doesn't seem to do anything. Is this a known issue? Are there workarounds?

Thanks!
Marco

**Comment by yurikoles** [comment]
Hi Marco,

I assume that you had installed `konsole` from [Homebrew KDE](https://invent.kde.org/packaging/homebrew-kde). If it's reproducible with [build from KDE's Jenkins](https://binary-factory.kde.org/view/MacOS/job/Konsole_Nightly_macos/lastStableBuild/), then it should be [reported directly to the `konsole` project](https://bugs.kde.org/enter_bug.cgi?product=konsole). If issue is observed only in build from Homebrew KDE, then it should be reported on [Homebrew KDE Invent project](https://invent.kde.org/packaging/homebrew-kde/-/issues).

This repo is completely unrelated to `konsole`.

**Comment by yurikoles** [comment]
I forgot to mention that Ctrl works on my machine in both versions: from Homebrew formula and from Jenkins.

**Comment by marcovc** [comment]
Thanks for the info!
