### ISSUE TITLE
Unable to install Far from Brew command

### ISSUE THREAD

**Issue by tilperion2** [yurikoles/homebrew-yurikoles#2]
Hi, I was trying to intall Far using homeBrew on my Mac. 
But brew failed to complete. 
I have:
 OS: 10.14.6, Mojave
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro15,1
  Processor Name:	Intel Core i7
  Processor Speed:	2,2 GHz
  Number of Processors:	1
  Total Number of Cores:	6
  L2 Cache (per Core):	256 KB
  L3 Cache:	9 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
Apple clang version 11.0.0 (clang-1100.0.20.17)

**Here is the output that I have:**

`brew install yurikoles/yurikoles/far2l
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
No changes to formulae.

==> Installing far2l from yurikoles/yurikoles
==> Downloading https://github.com/elfmz/far2l/archive/alpha-23jun19.tar.gz
Already downloaded: /Users/user/Library/Caches/Homebrew/downloads/701b251ddc0c87c915fda7ede18b37367be19832cbc4eeceec34c2a431c26753--far2l-alpha-23jun19.tar.gz
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/far2l/0.2-alpha.201
==> make install
Last 15 lines from /Users/user/Library/Logs/Homebrew/far2l/02.make:
cd /tmp/far2l-20200107-32618-5wig2p/far2l-alpha-23jun19/far2l/bootstrap/scripts && gawk -f /tmp/far2l-20200107-32618-5wig2p/far2l-alpha-23jun19/far2l/bootstrap/scripts/mkhlf.awk /tmp/far2l-20200107-32618-5wig2p/far2l-alpha-23jun19/far2l/bootstrap/scripts/FarRus.hlf.m4 | m4 -P -DARCH=Darwin\ x86_64 > /tmp/far2l-20200107-32618-5wig2p/far2l-alpha-23jun19/far2l/bootstrap/FarRus.hlf
fatal: not a git repository (or any of the parent directories): .git
hun
cd /tmp/far2l-20200107-32618-5wig2p/far2l-alpha-23jun19/far2l/bootstrap/scripts && gawk -f /tmp/far2l-20200107-32618-5wig2p/far2l-alpha-23jun19/far2l/bootstrap/scripts/mkhlf.awk /tmp/far2l-20200107-32618-5wig2p/far2l-alpha-23jun19/far2l/bootstrap/scripts/FarHun.hlf.m4 | m4 -P -DARCH=Darwin\ x86_64 > /tmp/far2l-20200107-32618-5wig2p/far2l-alpha-23jun19/far2l/bootstrap/FarHun.hlf
fatal: not a git repository (or any of the parent directories): .git
languages
cd /tmp/far2l-20200107-32618-5wig2p/far2l-alpha-23jun19/far2l/bootstrap && /tmp/far2l-20200107-32618-5wig2p/far2l-alpha-23jun19/tools/farlng generator -nc -i /tmp/far2l-20200107-32618-5wig2p/far2l-alpha-23jun19/far2l/bootstrap/lang.ini -ol /tmp/far2l-20200107-32618-5wig2p/far2l-alpha-23jun19/far2l/bootstrap /tmp/far2l-20200107-32618-5wig2p/far2l-alpha-23jun19/far2l/bootstrap/farlang.templ
dyld: Symbol not found: __ZTISt12length_error
  Referenced from: /tmp/far2l-20200107-32618-5wig2p/far2l-alpha-23jun19/tools/farlng
  Expected in: /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
 in /tmp/far2l-20200107-32618-5wig2p/far2l-alpha-23jun19/tools/farlng
/bin/sh: line 1: 36442 Abort trap: 6           /tmp/far2l-20200107-32618-5wig2p/far2l-alpha-23jun19/tools/farlng generator -nc -i /tmp/far2l-20200107-32618-5wig2p/far2l-alpha-23jun19/far2l/bootstrap/lang.ini -ol /tmp/far2l-20200107-32618-5wig2p/far2l-alpha-23jun19/far2l/bootstrap /tmp/far2l-20200107-32618-5wig2p/far2l-alpha-23jun19/far2l/bootstrap/farlang.templ
make[2]: *** [bootstrap] Error 134
make[1]: *** [far2l/bootstrap/CMakeFiles/bootstrap.dir/all] Error 2
make: *** [all] Error 2
`

**Comment by yermak** [comment]
I have similar issue, while installing from brew:

`brew install --HEAD yurikoles/yurikoles/far2l`

![image](https://user-images.githubusercontent.com/380491/99150638-dd4d3180-268d-11eb-990f-6ba013141a3d.png)

`Last 15 lines from /Users/yermak/Library/Logs/Homebrew/far2l/01.cmake:
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2") 
-- generating headers and languages
CMake Error at /usr/local/Cellar/cmake/3.18.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find Uchardet (missing: UCHARDET_LIBRARY UCHARDET_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.18.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindUchardet.cmake:16 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  far2l/CMakeLists.txt:156 (find_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/far2l-20201114-26435-795ibw/build/CMakeFiles/CMakeOutput.log".`

**Comment by yurikoles** [comment]
Should be fixed in 1cdf19730c39612c306c4710397e85ad3d4a3b1f
