### ISSUE TITLE
Failed install on MacOS

### ISSUE THREAD

**Issue by vhodus** [yurikoles/homebrew-yurikoles#7]
Hi) I was trying to install Far using homeBrew on Mac. But smthng went wrong.

---
my config:

	OSX Mojave 10.14
	MacBook Air early 2015, A1466
	1,6 GHz Intel Core i5
	4 Gb 1600 MHz DDR3
	Intel HD Graphics 6000 1536 МБ
	Apple LLVM version 10.0.1 (clang-1001.0.46.4)
---

brew install yurikoles/yurikoles/far2l

Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
nicotine-plus                                                                             openjdk@8
==> Updated Formulae
Updated 89 formulae.
==> New Casks
ddnet                               imarisviewer                        lx-music                            solar2d                             yuque
==> Updated Casks
5kplayer                      keycue                        origin                        scrutiny                      tableplus                     usenapp
a-better-finder-attributes    kite                          piezo                         session-manager-plugin        termius                       virtualbox
adobe-dng-converter           lingo                         polar-bookshelf               signal                        ticktick                      virtualbox-extension-pack
amazon-chime                  minitube                      postbox                       simplenote                    timeular                      wechat
electron                      moneymoney                    proclaim                      sipgate-softphone             tongbu                        wordpresscom
element                       mplabx-ide                    protonmail-bridge             sizzy                         tor-browser
exodus                        mullvadvpn                    publii                        slite                         torguard
firefox                       mymonero                      raven-reader                  smartsvn                      tunnelbear
fontexplorer-x-pro            ocenaudio                     reaper                        snagit                        twist
google-chrome                 opera                         reunion                       syncplay                      ubersicht
==> Deleted Casks
coronasdk

==> Tapping yurikoles/yurikoles
Cloning into '/usr/local/Homebrew/Library/Taps/yurikoles/homebrew-yurikoles'...
remote: Enumerating objects: 118, done.
remote: Counting objects: 100% (118/118), done.
remote: Compressing objects: 100% (87/87), done.
remote: Total 271 (delta 46), reused 102 (delta 31), pack-reused 153
Receiving objects: 100% (271/271), 84.76 KiB | 99.00 KiB/s, done.
Resolving deltas: 100% (106/106), done.
Tapped 7 casks and 8 formulae (42 files, 135.2KB).
Error: yurikoles/yurikoles/far2l is a head-only formula
Install with `brew install --HEAD yurikoles/yurikoles/far2l`

---

brew install yurikoles/yurikoles/far2l --HEAD

Updating Homebrew...
==> Installing far2l from yurikoles/yurikoles
==> Downloading https://homebrew.bintray.com/bottles/cmake-3.18.4.mojave.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/a0b167ad7f2fbf6f6dbcca9d74cb09acbd7822c54873803e940abf04272f8028?response-content-disposition=attachment%3Bfilename%3D%
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/ninja-1.10.1_2.mojave.bottle.tar.gz
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/mpfr-4.1.0.mojave.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/93c0d2ca093819f125300002cd34c1d1b4dfb7a1403729205861bec21388ff12?response-content-disposition=attachment%3Bfilename%3D%
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/gawk-5.1.0.mojave.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/ddbb56c56d66f375147769a27301e2ffd099abdc07f5dfc16389af22028e185b?response-content-disposition=attachment%3Bfilename%3D%
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/libb2-0.98.1.mojave.bottle.tar.gz
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/lz4-1.9.2.mojave.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/67ca428e60e2c2f6e524dd3de42629c1a616d28b2c743b66bf4cbdcc3b28ea46?response-content-disposition=attachment%3Bfilename%3D%
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/zstd-1.4.5.mojave.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/86b04bfd318315486d772b29d30b361e734a74269ae48805eeb3eae1d562b984?response-content-disposition=attachment%3Bfilename%3D%
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/libarchive-3.4.3.mojave.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/5cdfab0da88b4a1141cd2f512ad2815f69191bf7d9adc49e0cb9c814af286688?response-content-disposition=attachment%3Bfilename%3D%
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/libssh-0.9.5.mojave.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/9f7af086488d919155cd0c72a66a914b27d278a74d6231d77b07bbafff25ec33?response-content-disposition=attachment%3Bfilename%3D%
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/neon-0.31.2.mojave.bottle.tar.gz
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/wget-1.20.3_2.mojave.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/28f4090610946a4eb207df102d841de23ced0d06ba31cb79e040d883906dcd4f?response-content-disposition=attachment%3Bfilename%3D%
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/wxmac-3.0.5.1_1.mojave.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/5f703423fc3f1e36d647a2d8be2d271a92f5d60f49ceba8e3478391bbd4f5303?response-content-disposition=attachment%3Bfilename%3D%
######################################################################## 100.0%
==> Cloning https://github.com/elfmz/far2l.git
Cloning into '/Users/macbookair/Library/Caches/Homebrew/far2l--git'...
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
==> Installing dependencies for yurikoles/yurikoles/far2l: cmake, ninja, mpfr, gawk, libb2, lz4, zstd, libarchive, libssh, neon, wget and wxmac
==> Installing yurikoles/yurikoles/far2l dependency: cmake
==> Pouring cmake-3.18.4.mojave.bottle.tar.gz
==> Caveats
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/cmake
==> Summary
🍺  /usr/local/Cellar/cmake/3.18.4: 6,263 files, 60.2MB
==> Installing yurikoles/yurikoles/far2l dependency: ninja
==> Pouring ninja-1.10.1_2.mojave.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/ninja/1.10.1_2: 7 files, 252.4KB
==> Installing yurikoles/yurikoles/far2l dependency: mpfr
==> Pouring mpfr-4.1.0.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/mpfr/4.1.0: 29 files, 5.1MB
==> Installing yurikoles/yurikoles/far2l dependency: gawk
==> Pouring gawk-5.1.0.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/gawk/5.1.0: 90 files, 4.6MB
==> Installing yurikoles/yurikoles/far2l dependency: libb2
==> Pouring libb2-0.98.1.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/libb2/0.98.1: 8 files, 238.6KB
==> Installing yurikoles/yurikoles/far2l dependency: lz4
==> Pouring lz4-1.9.2.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/lz4/1.9.2: 22 files, 581KB
==> Installing yurikoles/yurikoles/far2l dependency: zstd
==> Pouring zstd-1.4.5.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/zstd/1.4.5: 27 files, 3MB
==> Installing yurikoles/yurikoles/far2l dependency: libarchive
==> Pouring libarchive-3.4.3.mojave.bottle.tar.gz
==> Caveats
libarchive is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have libarchive first in your PATH run:
  echo 'export PATH="/usr/local/opt/libarchive/bin:$PATH"' >> ~/.zshrc

For compilers to find libarchive you may need to set:
  export LDFLAGS="-L/usr/local/opt/libarchive/lib"
  export CPPFLAGS="-I/usr/local/opt/libarchive/include"

For pkg-config to find libarchive you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/libarchive/lib/pkgconfig"

==> Summary
🍺  /usr/local/Cellar/libarchive/3.4.3: 62 files, 3.5MB
==> Installing yurikoles/yurikoles/far2l dependency: libssh
==> Pouring libssh-0.9.5.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/libssh/0.9.5: 22 files, 576.6KB
==> Installing yurikoles/yurikoles/far2l dependency: neon
==> Pouring neon-0.31.2.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/neon/0.31.2: 179 files, 713.4KB
==> Installing yurikoles/yurikoles/far2l dependency: wget
==> Pouring wget-1.20.3_2.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/wget/1.20.3_2: 50 files, 4.0MB
==> Installing yurikoles/yurikoles/far2l dependency: wxmac
==> Pouring wxmac-3.0.5.1_1.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/wxmac/3.0.5.1_1: 813 files, 23.1MB
==> Installing yurikoles/yurikoles/far2l --HEAD
==> cmake .. -G Ninja
Last 15 lines from /Users/macbookair/Library/Logs/Homebrew/far2l/01.cmake:
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2")
-- generating headers and languages
CMake Error at /usr/local/Cellar/cmake/3.18.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find Uchardet (missing: UCHARDET_LIBRARY UCHARDET_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.18.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindUchardet.cmake:16 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  far2l/CMakeLists.txt:155 (find_package)

-- Configuring incomplete, errors occurred!
See also "/tmp/far2l-20201021-64883-pf3hzn/build/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/yurikoles/homebrew-yurikoles/issues

These open issues may also help:
fixed missed dependencies in far2l.rb https://github.com/yurikoles/homebrew-yurikoles/pull/6
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC.

---

cant see log file, because directory ( /tmp/far2l-20201021-64883-pf3hzn/... ) does not exist

**Comment by vhodus** [comment]
i install Uchardet: 
	brew install Uchardet

and Spdlog:
	brew install Spdlog

---
after try one more time, failed

brew install --HEAD yurikoles/yurikoles/far2l

Updating Homebrew...
==> Installing far2l from yurikoles/yurikoles
==> Cloning https://github.com/elfmz/far2l.git
Updating /Users/macbookair/Library/Caches/Homebrew/far2l--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at aee26c9 fix Ins/Del in codepages menu (close #818)
==> cmake .. -G Ninja
Last 15 lines from /Users/macbookair/Library/Logs/Homebrew/far2l/01.cmake:
CMake Warning at CMakeLists.txt:231 (message):
  Python plugin not enabled by default, use -DPYTHON=yes if you really
  want it


-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/tmp/far2l-20201022-74962-1lns5g3/colorer/XERCESC_INCLUDE_DIR
   used as include directory in directory /tmp/far2l-20201022-74962-1lns5g3/colorer
/tmp/far2l-20201022-74962-1lns5g3/colorer/src/Colorer-library/src/XERCESC_INCLUDE_DIR
   used as include directory in directory /tmp/far2l-20201022-74962-1lns5g3/colorer/src/Colorer-library/src

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/yurikoles/homebrew-yurikoles/issues

These open issues may also help:
fixed missed dependencies in far2l.rb https://github.com/yurikoles/homebrew-yurikoles/pull/6
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC.

**Comment by SkyWriter** [comment]
@vhodus please check if https://github.com/elfmz/far2l/issues/820#issuecomment-714384460 helps

**Comment by vhodus** [comment]
@SkyWriter, thank you!

in my case, first install:

	brew install minizip
	brew install xerces-c
	brew install uchardet
	brew install Uchardet
	brew install Spdlog

and after:

	brew install --HEAD yurikoles/yurikoles/far2l

It works
